### ISSUE TITLE
Adding GitHub action

### ISSUE THREAD

**Issue by peter279k** [pH-7/JustHttpStatusCodes#1]
As title, I think it's nice to add this feature to make this PHP package tested during GitHub workflows building.

**Comment by pH-7** [comment]
That's an excellent idea @peter279k! Would you like to create a Pull Request for this project that adds a .github workflow which would trigger `composer run test` or something like?

**Comment by peter279k** [comment]
Thanks for your reply. Sure! I can create the PR to do that :).

**Comment by pH-7** [comment]
> Thanks for your reply. Sure! I can create the PR to do that :).

Awesome then! 🎉
